### ISSUE TITLE
Sample of IMDSv2 activation

### ISSUE THREAD

**Issue by adrienpessu** [awsdocs/elastic-beanstalk-samples#105]
Hi,

Would you mind adding a sample to enable IMDSv2. I know I can activate with the CLI : 
```
aws ec2 run-instances \
    --image-id ami-1a2b3c4d \
    --instance-type c3.large \
    --key-name MyKeyPair \
    --metadata-options "HttpEndpoint=enabled,HttpTokens=required"
```

But I can't find any resources to do it with ebextensions.

Thanks a lot in advance.

**Comment by dankhen** [comment]
@adrienpessu, I'll follow up with the Elastic Beanstalk team and post here with any info I get. Thanks!

**Comment by dankhen** [comment]
@adrienpessu At this time, Elastic Beanstalk doesn't support IMDSv2. This isn't just about configuration; we'd have to update our on-instance logic and software to support IMDSv2.
Also, note that if you attempt to modify the instance metadata option for an EC2 instance managed by Beanstalk to enforce IMDSv2 (disable IMDSv1), then the Beanstalk environment will break.

We're aware of this need and are tracking it internally. You're welcome to add a request for it on our [public roadmap](https://github.com/aws/elastic-beanstalk-roadmap).
