### ISSUE TITLE
Instancecert input

### ISSUE THREAD

**Issue by fsajwani** [awsdocs/elastic-beanstalk-samples#108]
when adding the instancecert for nodejs to my .ebextensions folder, what do I put in the following area. My certificate is a public one issues by AWS certificate manager.

   Default: |
      -----BEGIN CERTIFICATE-----
      Paste your public certificate content here
      -----END CERTIFICATE-----

**Comment by dankhen** [comment]
AWS Certificate Manager (ACM) certificates can attach to load balancers, but not to EC2 instances. So in this case, when you need to terminate at an instance and attach a certificate to the instance, they won't work.
You'll need to use a non-ACM certificate on the instance.
An engineer on our team found this: https://stackoverflow.com/questions/48386839/aws-elastic-beanstalk-nodejs-get-certificate-ssl-from-letsencrypt-without-be
