### ISSUE TITLE
Update drupal and wordpress samples to use Nginx.

### ISSUE THREAD

**Issue by neerajklite** [awsdocs/elastic-beanstalk-samples#110]
php 7.4 is only supported by Amazon linux 2 which only supports Nginx. Would be great if there are updates to the samples and docs on how to setup with load balanced auto scaled drupal and wordpress on elastic beanstalk. thanks :)

**Comment by dankhen** [comment]
@neerajklite You're right. We have a very large number of examples that need an update to support AL2. We'll do our best over a period of time to do that, as our resources permit. Sorry for the delay.
