### ISSUE TITLE
Cloud watch stream

### ISSUE THREAD

**Issue by soulpresidente** [awsdocs/elastic-beanstalk-samples#116]
I want to stream tomcat catalinat.out logs to cloud watch:

**This is my onfig :** 

packages:
  yum:
    awslogs: []

files:
  "/etc/awslogs/awscli.conf":
    mode: "000600"
    owner: root
    group: root
    content: |
      [plugins]
      cwlogs = cwlogs
      [default]
      region = `{"Ref":"AWS::Region"}`

  "/etc/awslogs/awslogs.conf":
    mode: "000600"
    owner: root
    group: root
    content: |
      [general]
      state_file = /var/lib/awslogs/agent-state

files:
  "/etc/awslogs/config/logs.conf":
    mode: "000600"
    owner: root
    group: root
    content: |
      [/var/log/tomcat8/catalina.out]
      log_group_name = `{"Fn::Join":["/", ["/aws/elasticbeanstalk", { "Ref":"AWSEBEnvironmentName" }, "/var/log/tomcat8/catalina.out"]]}`
      log_stream_name = {instance_id}
      file = /var/log/tomcat8/catalina.out

commands:
  "01":
    command: chkconfig awslogs on
  "02":
    command: service awslogs restart

But I don't see catalina.out in cloudwatch console : 
![image](https://user-images.githubusercontent.com/24256211/82341567-2292ee00-99e0-11ea-80d8-879e23122494.png)

**Comment by soulpresidente** [comment]
This is error , I have in awslogs.log How can I solve it. 2020-05-22 18:15:55,450 - cwlogs.push.batch - WARNING - 3374 - Thread-29 - CreateLogGroup failed with exception An error occurred (AccessDeniedException) when calling the CreateLogGroup operation: User: arn:aws:sts::610232524349:assumed-role/aws-elasticbeanstalk-ec2-role/i-099300c0bfd4b6a28 is not authorized to perform: logs:CreateLogGroup on resource: arn:aws:logs:eu-central-1:610232524349:log-group:/aws/elasticbeanstalk/************/var/log/tomcat8/catalina.out:log-stream:

**Comment by markotitel** [comment]
@soulpresidente you need to add policy logs:CreateLogGroup
It is not there by default.

**Comment by soulpresidente** [comment]
@markotitel how to add it?

**Comment by markotitel** [comment]
In the IAM roles. ElasticBeanstalk instance role is missing it.
The default is like this
```
        {
            "Sid": "CloudWatchLogsAccess",
            "Action": [
                "logs:PutLogEvents",
                "logs:CreateLogStream",
                "logs:DescribeLogStreams",
                "logs:DescribeLogGroups"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:logs:*:*:log-group:/aws/elasticbeanstalk*"
            ]
        }
```
You'll need to add `logs:CreateLogGroup`.

**Comment by soulpresidente** [comment]
thanks @markotitel
