### ISSUE TITLE
How to Load mod_rewrite.so in apache EB 

### ISSUE THREAD

**Issue by erick1979** [awsdocs/elastic-beanstalk-samples#118]
I wold like to know how I load rewrite_module:  "LoadModule rewrite_module modules/mod_rewrite.so".

I was in my os editing the file [apache2/httpd.conf] in AWS EB not start the module. 

What I need to do?

**Comment by mrenneke-amazon** [comment]
Hi @erick1979 --

I'm sorry you're having this issue.  This specific repo is for documentation issues, but I can point you to some other resources that may offer help:

* Try our forum: https://forums.aws.amazon.com/forum.jspa?forumID=86.
* Contact AWS Support: https://aws.amazon.com/premiumsupport/

Sorry about how long it took us to get back to you. I hope that you have found a solution or do so soon!

Thanks!
