### ISSUE TITLE
Insufficient data

### ISSUE THREAD

**Issue by tiago0289** [awsdocs/elastic-beanstalk-samples#121]
Hello.

Thank you. Your script and config files help me a lot.
Maybe I have found a little problem.
I'm trying to use the **autoscaling-memory-utilization.config**, but I had a problem. The alarm that is created shows insufficient data, reading the config file I realized that the alarm search for information about a metric called **MemoryUtilization** however, this metric does not exist and is not created by the script, so the alarm will always be in insufficient data and the scaling will never happen by memory.
Thank you.

**Comment by chanlito** [comment]
Hey @tiago0289 I had the same issue. Have you seen this https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customize-containers-cw.html#customize-containers-cw-update-roles ?

**Comment by tiago0289** [comment]
Hi @chanlito. 
I had already seen it, but I thought that the permissions I had set would replace it well. I configured it according to the documentation and it worked very well. Thanks for your help.
