### ISSUE TITLE
BeanStalk Python mount EFS not exist /opt/elasticbeanstalk/bin/get-config 

### ISSUE THREAD

**Issue by Virako** [awsdocs/elastic-beanstalk-samples#129]
I am using Python 3.7 AL2 version 3.0.2, 64bit Amazon Linux 2 v3.0.2 running Python 3.7 BeanStalk, and have a problem when try to mount EFS. The script said that /opt/elasticbeanstalk/bin/get-config not exist.

Is there some alternatives for get environment variables?

Thanks

**Comment by bahoo** [comment]
A very unglamorous solution, but hoping some better alternative emerges:

https://forums.aws.amazon.com/thread.jspa?threadID=321782

**Comment by tomchiverton** [comment]
get-config is present on newer AL2's

**Comment by mrenneke-amazon** [comment]
Hi @Virako -

Sorry you're having this issue and how long it took us to get back to you.  This channel is for documentation issues, but I'll point you to some other resources that can help:

* Try our forum: https://forums.aws.amazon.com/forum.jspa?forumID=86.
* Contact AWS Support: https://aws.amazon.com/premiumsupport/

Thanks!
