### ISSUE TITLE
showing error while mounting the efs file

### ISSUE THREAD

**Issue by hetul99** [awsdocs/elastic-beanstalk-samples#130]
Followed the following procedure for attaching the EFS file to instances created using EB.

https://aws.amazon.com/premiumsupport/knowledge-center/elastic-beanstalk-mount-efs-volumes/#:~:text=In%20an%20Elastic%20Beanstalk%20environment,scale%20up%20to%20multiple%20instances.

 But the logs of EB are showing following error:
[Instance: i-06593*****] Command failed on instance. Return code: 1 Output: (TRUNCATED)...fs ... mount -t efs -o tls fs-d9****:/ /efs Failed to resolve "fs-d9****.efs.us-east-1.amazonaws.com" - check that your file system ID is correct. See https://docs.aws.amazon.com/console/efs/mount-dns-name for more detail. ERROR: Mount command failed!. command 01_mount in .ebextensions/storage-efs-mountfilesystem.config failed. For more detail, check /var/log/eb-activity.log using console or EB CLI.

Just used  **** in EFS ID for security.
Please help to resolve the issue

**Comment by mrenneke-amazon** [comment]
Hi @hetul99 

Sorry to see you're having this issue.  This channel is for the Elastic Beanstalk [samples repo](https://github.com/awsdocs/elastic-beanstalk-samples), but I can point you to resources that can offer you help:

* Submit feedback on the above article from its web page.  The feedback button is on the bottom right of the page.  You can also contact AWS support from the same knowledge article page.
* Contact AWS Support: https://aws.amazon.com/premiumsupport/
* You can also try our forum: https://forums.aws.amazon.com/forum.jspa?forumID=86.

Thanks!
