### ISSUE TITLE
The perl-Bundle-LWP package cannot be found

### ISSUE THREAD

**Issue by jpaulorio** [awsdocs/elastic-beanstalk-samples#135]
https://github.com/awsdocs/elastic-beanstalk-samples/blob/1d2c5ead4033822cf8b265ae6b7986ed79c00632/configuration-files/aws-provided/resource-configuration/autoscaling-memory-utlization.config#L28

**Comment by dankhen** [comment]
@jpaulorio Does the config file cause a failure or another kind of error?

**Comment by dankhen** [comment]
Thanks @jpaulorio . I will pass the issue on to the Elastic Beanstalk team.

**Comment by dankhen** [comment]
(Sorry, closed by mistake.)

**Comment by spiderhands** [comment]
any update on this?

**Comment by vahiwe** [comment]
Please any update on this?

**Comment by GoPro16** [comment]
it hurts to not read the fine print in the article 😆 

> Important: For Amazon Linux 2 based platforms, replace the perl-Bundle-LWP yum package in the preceding configuration file with perl-Digest-SHA.

Did that and worked!

[Reference](https://aws.amazon.com/premiumsupport/knowledge-center/elastic-beanstalk-memory-monitoring/)

**Comment by dankhen** [comment]
Good catch @GoPro16. We will look into updating the example for AL2 and keeping the current one as a legacy version. Thanks!
