### ISSUE TITLE
HTTPS for Python on Amazon Linux 2

### ISSUE THREAD

**Issue by tg2648** [awsdocs/elastic-beanstalk-samples#137]
Hello,

Current documentation and config files for setting up HTTPS do not apply to Amazon Linux 2 running Python with gunicorn/nginx. I used the following two steps on Amazon Linux running Apache:

- [Terminating HTTPS on EC2 instances running Python](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/https-singleinstance-python.html)
-  [HTTPS redirection config file](https://github.com/awsdocs/elastic-beanstalk-samples/blob/master/configuration-files/aws-provided/security-configuration/https-redirect/python/https-redirect-python.config)

Any help is much appreciated!

**Comment by giancar70** [comment]
Hi  @tg2648 add this file [alb-http-to-https-redirection.config](https://github.com/awsdocs/elastic-beanstalk-samples/blob/master/configuration-files/aws-provided/resource-configuration/alb-http-to-https-redirection.config) inside project/.ebextensions/alb-http-to-https-redirection.config

**Comment by mrenneke-amazon** [comment]
Hello @tg2648  and @giancar70 -

I'm sorry about how long it took to respond to this issue.  We will take a look at your suggestion and consider adding it to our documentation.

Thank you for your help with this issue.
