### ISSUE TITLE
Unable to run cron on AMI 2 PHP Laravel due to environment variables not being accessible

### ISSUE THREAD

**Issue by Ali-Shaikh** [awsdocs/elastic-beanstalk-samples#141]
I have followed the instruction here 
https://aws.amazon.com/premiumsupport/knowledge-center/elastic-beanstalk-env-variables-linux2/

and then created a corn like this
```
#!/bin/sh

# Create CRON files

# After the deployment finishes, set up a Crontab for
# the php artisan schedule:run command
echo "* * * * * ec2-user source <(sed -E -n 's/[^#]+/export &/ p' /opt/elasticbeanstalk/deployment/envvars) && /usr/bin/php /var/app/current/artisan schedule:run 1>> /dev/null 2>&1" \
  | sudo tee /etc/cron.d/artisan_scheduler
```

but it is not working. The application fails to execute the commands because the env vars are not accessible. I have tried creating cron jobs for `root, webapp and ec2-user` users but nothing is working.

Any help I can get would be much appreciated.

**Comment by Ali-Shaikh** [comment]
Managed to figure it out https://github.com/AWSomeTech/aws-eb-laravel

**Comment by ma-za-kpe** [comment]
So the link you shared is broken
