### ISSUE TITLE
Thank you for the feedback. I merged your pull request, and the update will be published to the Lightsail docs soon.

### ISSUE THREAD

**Issue by kadoned** [awsdocs/elastic-beanstalk-samples#162]
Thank you for the feedback. I merged your pull request, and the update will be published to the Lightsail docs soon.

_Originally posted by @rlatino in https://github.com/awsdocs/amazon-lightsail-developer-guide/issues/39#issuecomment-767016613_

**Comment by mrenneke-amazon** [comment]
Closing this issue.

**Comment by mrenneke-amazon** [comment]
This comment pertains to Lightsail.  Closing this issue, as it's been addressed by Lighsail writer.
