### ISSUE TITLE
 CloudWatch Log Streaming No Longer Works on AL2023 since the awslogs is removed from AL2023

### ISSUE THREAD

**Issue by c0dezli** [awsdocs/elastic-beanstalk-samples#169]
Please update https://github.com/awsdocs/elastic-beanstalk-samples/blob/master/configuration-files/aws-provided/instance-configuration/logs-streamtocloudwatch-linux.config

**Comment by hughkelsey** [comment]
I ran in to this myself and added a PR for some more up to date docs: https://github.com/awsdocs/elastic-beanstalk-samples/pull/170

**Comment by daintym0sh** [comment]
> I ran in to this myself and added a PR for some more up to date docs: #170

Thanks for this! I was also having trouble setting up logs with AL2023.

**Comment by mrenneke-amazon** [comment]
Thank you for submitting this issue and for [contributing the sample configuration](https://github.com/awsdocs/elastic-beanstalk-samples/pull/170) for AL2023.  

We have updated the outdated configuration file to work with both AL2 and AL2023.  Please see this now merged [Pull Request](https://github.com/awsdocs/elastic-beanstalk-samples/pull/174) for details.

We have also updated the Elastic Beanstalk Developer Guide, in the [Custom log file streaming](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/AWSHowTo.cloudwatchlogs.html#AWSHowTo.cloudwatchlogs.streaming) section,  to reference the most current CloudWatch agent configuration file information.
