### ISSUE TITLE
Symfony 2 deployment configuration

### ISSUE THREAD

**Issue by samsch** [awsdocs/elastic-beanstalk-samples#17]
Part of the deployment for Symfony 2/3 is handling the app configuration (as stored in `app/config/parameters.yml` and templated by `app/config/parameters.yml.dist`). At the moment, the process defaults to the values in `parameters.yml.dist`, which is meant to be committed to VC and to contain only placeholder or null values for sensitive parameters (e.g. db user/password, api keys, etc).

Could the [documentation](https://github.com/awslabs/elastic-beanstalk-docs/blob/master/tutorials/php/symfony2/tutorial-deploy-symfony2-application-aws-elastic-beanstalk.md) be expanded to include a section about how to properly handle app config with EB? Or, if that information is available in another article, could a mention and link be made?

**Comment by MHaendel** [comment]
Have you tried with environment variables? 
I would love to have some more infos too.

`SYMFONY__DATABASE_NAME`

**Comment by samsch** [comment]
That is eventually what I did for my apps, using something similar to the article you linked.

**Comment by mwunderl** [comment]
Hi samsch and MHaendel,

Thanks for the info. There's some helpful info in the Symfony docs:
[Moving secrets out of configuration](http://symfony.com/doc/current/best_practices/configuration.html#moving-sensitive-options-outside-of-symfony-entirely)
[External parameters](http://symfony.com/doc/current/configuration/external_parameters.html)

With Symfony 3.2+, you can use env() parameters to access Beanstalk database connection variables like RDS_PASSWORD. In older versions you need to use SYNFONY__ style variables.

I'll add some info to the [PHP database configuration topic](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_PHP.rds.html) in the developer guide and update the tutorial to link to that.

Thanks,
-Michael

**Comment by mwunderl** [comment]
added https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_PHP.rds.html#php-rds-symfony
