### ISSUE TITLE
Should I fork the master branch or the main branch?

### ISSUE THREAD

**Issue by amoshimei** [awsdocs/elastic-beanstalk-samples#172]
I would like to add a file to this repository. However, I am uncertain about which branch to fork. Should I fork the master branch or the main branch?

The reason for my confusion is as follows: The README states, "In your fork, make your change in a branch that's based on this repo's master branch." However, the main branch appears to be the default and the most up-to-date branch.

I am a beginner in both English and contributing to OSS.
Thank you for your guidance.

**Comment by mrenneke-amazon** [comment]
Hi @amoshimei,
Please use the _main_ branch.  
I've updated the README file to refer to the _main_ branch instead.

Thank you for your participation!

**Comment by amoshimei** [comment]
Hi @mrenneke-amazon,
Thank you for the adjustment.

We have sent you a pull request and I will provide the detailed background below.

Recently, I received an email from AWS notifying us of the deprecation of EC2 Auto Scaling Launch Configurations in favor of Launch Templates.

"EC2 Auto Scaling Launch Configuration Deprecation Notification
In 2021, AWS announced the plan to deprecate launch configurations in favor of launch templates. Since that time, continual enhancements have been made to encourage migration to launch templates. This notification contains details about the next step in the launch configuration deprecation process.

We strongly encourage the remaining customers of launch configurations to migrate to launch templates as soon as possible. Our documentation provides guidance on using the console migration tool to convert launch configurations to launch templates [1]. To identify Auto Scaling groups that are still using launch configurations, you can run this script [2]."

In response, I executed the eb create command. However, Beanstalk initiated Auto Scaling using the old Launch Configuration instead of the new Launch Template. Consequently, I had to create this configuration file.
