### ISSUE TITLE
Websockets with ALB and Ruby Passenger failed.

### ISSUE THREAD

**Issue by amrfaisal** [awsdocs/elastic-beanstalk-samples#62]
Hi,
We are using "64bit Amazon Linux 2017.09 v2.7.1 running Ruby 2.3 (Passenger Standalone)" configuration.
Added an ALB and tried to test Websockets and got "WebSocket is closed before the connection is established."

When switched to "Puma" stack, and added the NGINX config mentioned below, everything is working as expected.
https://github.com/awslabs/elastic-beanstalk-samples/blob/dd644f00e087b6b50e7ad0f69b6334f1dcc7cde7/configuration-files/aws-provided/instance-configuration/websockets/ruby-puma/websockets-ruby-puma.config

**Comment by dankhen** [comment]
@amrfaisal, I am sorry for the late response.
To make sure I understand: are you saying that the example that you linked to (websockets-ruby-puma.config) works? Which one doesn't work - is it [websockets-ruby-passenger.config](https://github.com/awsdocs/elastic-beanstalk-samples/blob/master/configuration-files/aws-provided/instance-configuration/websockets/ruby-passenger/websockets-ruby-passenger.config)?

**Comment by dankhen** [comment]
Closing the issue for inactivity.
Please feel free to reopen it with further information.
