### ISSUE TITLE
remove jq as a dependency for `get-config environment` commands

### ISSUE THREAD

**Issue by ozdanborne** [awsdocs/elastic-beanstalk-samples#69]
The examples on this repo use JQ to pull out specific fields in calls to `get-config`:

```
$(/opt/elasticbeanstalk/bin/get-config environment | jq -r '.MOUNT_DIRECTORY')
```

I wasted some time figuring out that not only is JQ not installed by default on most platforms, but you don't need it if you use `-k`

```
$(/opt/elasticbeanstalk/bin/get-config environment -k MOUNT_DIRECTORY)
```

**Comment by dankhen** [comment]
@ozdanborne, thanks for pointing this out.
The examples that use `jq` make sure it's installed on the instance by specifying it in the `packages:` section of the configuration file, thereby causing it to be installed.

However, for the subset of examples that use `get-config environment`, I agree with you that using `get-config environment -k` is more elegant than using an additional tool. I changed these examples to do that as you suggested.
