### ISSUE TITLE
Property HealthyThreshold cannot be empty.

### ISSUE THREAD

**Issue by AEKurt** [awsdocs/elastic-beanstalk-samples#72]
Hello, when I use aws-provided/resource-configuration/loadbalancer-accesslogs-existingbucket.config

I have encountered the "Creating load balancer failed Reason: Property HealthyThreshold cannot be empty."

Thanks.

**Comment by dankhen** [comment]
@AEKurt , did you configure your environment to have a load balancer? I believe this example is meant to add uploading access log to an S3 bucket to your environment's configured load balancer (it doesn't take care of creating the load balancer).

Also, is your load balancer a classic load balancer? This example works with a classic load balancer (resource name `AWS::ElasticLoadBalancing::LoadBalancer`). I'll clarify it in the example's comment.

Finally, if you use one of the newer load balancer types, network load balancer or application load balancer, you don't need the kind of configuration shown in this example. With these load balancer types, we support native Elastic Beanstalk options to enable uploading logs to S3 and to configure the S3 bucket. The options are in the `aws:elbv2:loadbalancer` namespace. You can also configure these options using the Elastic Beanstalk console.

Please let me know if any of this helps.

**Comment by AEKurt** [comment]
Thank you for your information. The environment that I have tried your configuration had no load balancer I have just realized that.
