### ISSUE TITLE
.ebextensions config mode should be quoted

### ISSUE THREAD

**Issue by NohSeho** [awsdocs/elastic-beanstalk-samples#74]
Hello, I find some issues about mode(file permission) in .ebextensions config for this samples.

https://github.com/awsdocs/elastic-beanstalk-samples/blob/4ae60e500ce566cbb5fff6b95338cea79c67e302/configuration-files/aws-provided/security-configuration/https-redirect/python/https-redirect-python.config#L28
Some mode values are not quoted, and that has wrong permission when deploy to server.

For instance:
That file should be `-rw-r--r--`, but the result is `-r---w----`

**Comment by dankhen** [comment]
Thanks @NohSeho, good point!
I fixed it in this file and another six config files that had the same issue.
