### ISSUE TITLE
nodejs platform uses upstart not sysVinit

### ISSUE THREAD

**Issue by finchd** [awsdocs/elastic-beanstalk-samples#77]
At least in nodejs platform 4.5.0+, nginx is started and stopped with 'initctl' not 'service'

Extensions that need to be modified:
configuration-files/aws-provided/security-configuration/https-redirect/nodejs/https-redirect-nodejs.config
configuration-files/aws-provided/instance-configuration/websockets/nodejs/websockets-nodejs.config

Rather than replacing `service nginx stop|start` with `initctl start|stop nginx`, logic needs to be added to detect which one is in use.

With the current https-redirect-nodejs.config, /var/log/eb-activity.log:
```
[2018-10-17T19:53:16.175Z] INFO  [27164] - [Configuration update xxx] : Activity execution failed, because: + rm -f /etc/nginx/conf.d/00_elastic_beanstalk_proxy.conf
  + service nginx stop
  Stopping nginx: /sbin/service: line 66: $pid Killed                  env -i PATH="$PATH" TERM="$TERM" "${SERVICEDIR}/${SERVICE}" ${OPTIONS} (ElasticBeanstalk::ExternalInvocationError)
caused by: + rm -f /etc/nginx/conf.d/00_elastic_beanstalk_proxy.conf
  + service nginx stop
  Stopping nginx: /sbin/service: line 66: $pid Killed                  env -i PATH="$PATH" TERM="$TERM" "${SERVICEDIR}/${SERVICE}" ${OPTIONS} (Executor::NonZeroExitStatus)
```

**Comment by zackshapiro** [comment]
@finchd Following up from our call yesterday, I found some further information for you:

I have two servers, Server A running a Classic Load Balancer, Server B running an Auto Load Balancer

Yesterday, on Server A, I was unable to add a config var. Your suggestion to change `service nginx stop|start` to `initctl stop|start nginx` worked and I was then able to update my config vars.

That subsequently broke my ability to add a config var to Server B, which after experimenting and replacing `initctl stop|start nginx` with `service nginx stop|start`, I was able to add a config var there.

So it seems to me to be load balancer related.

**Comment by finchd** [comment]
Its not possible to be load balancer related, but those two environments are probably on different platform versions - the ALB one is probably 4.4.5-

**Comment by zackshapiro** [comment]
Thanks @finchd. Where can I see which platform version my load balancer is on?

**Comment by dankhen** [comment]
@finchd , thanks for bringing this up. We'll look into the right way to update these config files.

**Comment by finchd** [comment]
@zackshapiro The EB Platform version would be upper-right in the Elastic Beanstalk Console.
Definitely test this in a non-production environment first, but you should upgrade the old EB environment to above 4.5.0 so they all use initctl instead of service.

**Comment by dankhen** [comment]
Thanks both for the discussion. We will pursue a change that covers more cases.

**Comment by dankhen** [comment]
@fincd, @zackshapiro: it took a while (sorry). I got back to this and fixed the example to accommodate both 'initctl' and 'service' for stopping/starting nginx. You're invited to review.
(Of course, the config example only configures Nginx to redirect HTTP to HTTPS. The load balancer and/or application code should be adapted accordingly.)
