### ISSUE TITLE
Is it possible to use this for Django https://github.com/awsdocs/elastic-beanstalk-samples/blob/master/configuration-files/aws-provided/security-configuration/https-redirect/python/https-redirect-python.config

### ISSUE THREAD

**Issue by flexpeace** [awsdocs/elastic-beanstalk-samples#79]

**Comment by dankhen** [comment]
@flexpeace , thanks for your question. We're looking into it.

**Comment by dankhen** [comment]
One of our engineers informed me that this example can't be used with Django. I'll make a note in the example. Thanks for bringing this up!

**Comment by ohlr** [comment]
What should Django users do instead? Besides terminating at the load balancer?
