### ISSUE TITLE
Websockets not working using WSS

### ISSUE THREAD

**Issue by fieldfoxWim** [awsdocs/elastic-beanstalk-samples#80]
https://github.com/awsdocs/elastic-beanstalk-samples/blob/117f05fd23c0598ac7c5bdf025c2203940aeffca/configuration-files/aws-provided/security-configuration/https-instancecert/https-instancecert-nodejs.config#L64

This line causes websockets to return a 401 when using a secure connection (wss://)

I replaced it with `proxy_set_header Connection "upgrade";`

**Comment by mcdwil** [comment]
@fieldfoxWim , thanks for bringing this up. We're looking into it.

**Comment by mcdwil** [comment]
@fieldfoxWim , we have a configuration file for enabling web socket support here: https://github.com/awsdocs/elastic-beanstalk-samples/blob/master/configuration-files/aws-provided/instance-configuration/websockets/nodejs/websockets-nodejs.config

After review with one of our engineers, we're going to keep the two separate. 

Thanks for bringing this up!

**Comment by fieldfoxWim** [comment]
@mcdwil that file is for unsecure websockets and not related to the issue. `Listen 8080` vs `Listen 443`

> we're going to keep the two separate.
Ofc I agree, I did not suggest to merge anything

Will the proxy_set_header be changed? Because this causes all `wss://` socket communication to fail.
