### ISSUE TITLE
Variables show as variables

### ISSUE THREAD

**Issue by universenl** [awsdocs/elastic-beanstalk-samples#84]
Hello,

I am trying to auto deploy aws eb and more services, now the following problem is coming up.
There is no way i get {"Ref" : "AWS::Region"} parsed in one of the .config files, even the sample is still showing the command instead of the value in the env.

Can you support on this ?

Greatings.

**Comment by mcdwil** [comment]
Thank you for contacting us!
 
I am sorry you were having trouble using our service.

For more information about environment properties, see [Environment Properties and Other Software Settings](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environments-cfg-softwaresettings.html) in the AWS Elastic Beanstalk Developer Guide.

If you need expert help or have questions about AWS Elastic Beanstalk, I can suggest the following:
· Try our forum: https://forums.aws.amazon.com/forum.jspa?forumID=86
· Contact AWS Support: https://aws.amazon.com/premiumsupport/
