### ISSUE TITLE
Python https redirect is not wokring for flask  Python 3.6 running on 64bit Amazon Linux/2.7.6.

### ISSUE THREAD

**Issue by hemande** [awsdocs/elastic-beanstalk-samples#85]
I was getting 500 errors with the sample flask application using the current ebextension found here

https://github.com/awsdocs/elastic-beanstalk-samples/blob/117f05fd23c0598ac7c5bdf025c2203940aeffca/configuration-files/aws-provided/security-configuration/https-redirect/python/https-redirect-python.config

Attached is the sample flask application with working https redirect for Python 3.6 running on 64bit Amazon Linux/2.7.6. 
[upload.zip](https://github.com/awsdocs/elastic-beanstalk-samples/files/2681506/upload.zip)

I believe the config.py script has been changed in the update.

**Comment by dankhen** [comment]
Fixed. Thanks for bringing it to our attention!
