### ISSUE TITLE
aws:autoscaling:trigger:EvaluationPeriods is not present in documentation.

### ISSUE THREAD

**Issue by taraslayshchuk** [awsdocs/elastic-beanstalk-samples#87]
[EvaluationPeriods](https://github.com/awsdocs/elastic-beanstalk-samples/blob/d16a9b5c0260a78d72d2e546a8dfd854c84bc973/configuration-files/aws-provided/resource-configuration/autoscaling-triggers-customize.config#L33) is not documented in [aws:autoscaling:trigger](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-autoscalingtrigger) AWS Elastic-Beanstalk documentation.

**Comment by dankhen** [comment]
Thanks for this @taraslayshchuk ! I'm looking into it.

**Comment by dankhen** [comment]
@taraslayshchuk , I've added a short description of `EvaluationPeriods`.
I'm still unhappy with the state of this namespace description; I'd like to clarify the exact relationship across `BreachDuration`, `Period`, and `EvaluationPeriods`. I'm researching that, and will update as soon as I have the information.
Thanks again for pointing this out.

**Comment by dankhen** [comment]
I made a clarification at the start of the `aws:autoscaling:trigger` namespace description. DL;DR: the 3 options have to satisfy a relationship, and if you specify inconsistent values, one of the values might be coerced such that the relationship is still satisfied.
