### ISSUE TITLE
How could I place or use the config file

### ISSUE THREAD

**Issue by aefkung** [awsdocs/elastic-beanstalk-samples#91]
I go in to dotnet folder and get the config file but I have no idea how to use it or place to which folder. Please enlight me. Thank you

**Comment by dankhen** [comment]
@aefkung, this is explained in the README at the [top of the repo](https://github.com/awsdocs/elastic-beanstalk-samples). In a nutshell: to use any of the example `.config` files, place them in a folder named `.ebextensions` in the root of your application source.

**Comment by aefkung** [comment]
Thank you a lot
