### ISSUE TITLE
env-regionname.config doesnt do what its supposed to

### ISSUE THREAD

**Issue by garrettgjb** [awsdocs/elastic-beanstalk-samples#96]
If you use env-regionname.config it creates a literal value of:`{"Ref" : "AWS::Region"}` in your options rather than the actual result of this operation.

**Comment by mcdwil** [comment]
Hi, thanks for getting in touch!

Just tested this, and the console shows the literal value, but on instance it does get resolved to the actual region. You can check environment variables on instance with `/opt/elasticbeanstalk/bin/get-config`. https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/custom-platforms-scripts.html
