### ISSUE TITLE
Need help on sidekiq with rails config file from aws official.

### ISSUE THREAD

**Issue by dineshPallapa** [awsdocs/elastic-beanstalk-samples#98]
I am using this config from this gist.
https://gist.github.com/MaxDBN/b80d6e5fac7f1a05f2727474ff172ea6

But not restarting after changing config environment variables.

Can you help on this @dankhen

**Comment by dankhen** [comment]
@dineshPallapa,
Please point out which specific config file you're having trouble with, and what you believe the issues are. We're happy to take a look. Thanks!

**Comment by dineshPallapa** [comment]
https://gist.github.com/MaxDBN/b80d6e5fac7f1a05f2727474ff172ea6

**Comment by dankhen** [comment]
Thanks @dineshPallapa. Issues on this documentation repo are meant to be about examples that we've posted on this repo. Unfortunately the AWS documentation team can't provide support beyond that.

I recommend that you ask the question on the [AWS Elastic Beanstalk forum](https://forums.aws.amazon.com/forum.jspa?forumID=86) or contact [AWS support](https://aws.amazon.com/premiumsupport/).
